model_list:
  - model_name: mistral-free
    litellm_params:
      model: openrouter/mistralai/mistral-7b-instruct:free
      api_key: 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

litellm_settings:
  drop_params: true
